micronaut:
  application:
    name: pos-message-tracker
  server:
    port: 8080
  router:
    static-resources:
      default:
        enabled: true
        mapping: "/**"
        paths: "classpath:public"
      swagger:
        enabled: false
